package com.tuanc.auc.entities;
// Generated Feb 28, 2023, 1:38:45 AM by Hibernate Tools 6.1.5.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Auction generated by hbm2java
 */
public class Auction implements java.io.Serializable {

	private Integer id;
	private Account account;
	private String title;
	private String description;
	private Timestamp startTime;
	private Timestamp endTime;
	private int changeStartTime;
	private byte levelDisplay;
	private boolean type;
	private String status;
	private Set categories = new HashSet(0);
	private Set comments = new HashSet(0);
	private Set tickets = new HashSet(0);
	private Set accounts = new HashSet(0);
	private Set products = new HashSet(0);

	public Auction() {
	}

	public Auction(Account account, String title, String description, Timestamp startTime, Timestamp endTime,
			int changeStartTime, byte levelDisplay, boolean type, String status) {
		this.account = account;
		this.title = title;
		this.description = description;
		this.startTime = startTime;
		this.endTime = endTime;
		this.changeStartTime = changeStartTime;
		this.levelDisplay = levelDisplay;
		this.type = type;
		this.status = status;
	}

	public Auction(Account account, String title, String description, Timestamp startTime, Timestamp endTime,
			int changeStartTime, byte levelDisplay, boolean type, String status, Set categories, Set comments,
			Set tickets, Set accounts, Set products) {
		this.account = account;
		this.title = title;
		this.description = description;
		this.startTime = startTime;
		this.endTime = endTime;
		this.changeStartTime = changeStartTime;
		this.levelDisplay = levelDisplay;
		this.type = type;
		this.status = status;
		this.categories = categories;
		this.comments = comments;
		this.tickets = tickets;
		this.accounts = accounts;
		this.products = products;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Timestamp getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Timestamp startTime) {
		this.startTime = startTime;
	}

	public Timestamp getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Timestamp endTime) {
		this.endTime = endTime;
	}

	public int getChangeStartTime() {
		return this.changeStartTime;
	}

	public void setChangeStartTime(int changeStartTime) {
		this.changeStartTime = changeStartTime;
	}

	public byte getLevelDisplay() {
		return this.levelDisplay;
	}

	public void setLevelDisplay(byte levelDisplay) {
		this.levelDisplay = levelDisplay;
	}

	public boolean isType() {
		return this.type;
	}

	public void setType(boolean type) {
		this.type = type;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getCategories() {
		return this.categories;
	}

	public void setCategories(Set categories) {
		this.categories = categories;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

	public Set getTickets() {
		return this.tickets;
	}

	public void setTickets(Set tickets) {
		this.tickets = tickets;
	}

	public Set getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set accounts) {
		this.accounts = accounts;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
