package com.tuanc.auc.entities;
// Generated Feb 28, 2023, 1:38:45 AM by Hibernate Tools 6.1.5.Final

import java.sql.Timestamp;

/**
 * BidLog generated by hbm2java
 */
public class BidLog implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Product product;
	private double price;
	private Timestamp time;

	public BidLog() {
	}

	public BidLog(Account account, Product product, double price, Timestamp time) {
		this.account = account;
		this.product = product;
		this.price = price;
		this.time = time;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Timestamp getTime() {
		return this.time;
	}

	public void setTime(Timestamp time) {
		this.time = time;
	}

}
