package com.tuanc.auc.entities;
// Generated Feb 28, 2023, 1:38:45 AM by Hibernate Tools 6.1.5.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Timestamp created;
	private String fileName;
	private double total;
	private double taxPercent;
	private double tradingFeePercent;
	private Set products = new HashSet(0);

	public Invoice() {
	}

	public Invoice(Account account, Timestamp created, String fileName, double total, double taxPercent,
			double tradingFeePercent) {
		this.account = account;
		this.created = created;
		this.fileName = fileName;
		this.total = total;
		this.taxPercent = taxPercent;
		this.tradingFeePercent = tradingFeePercent;
	}

	public Invoice(Account account, Timestamp created, String fileName, double total, double taxPercent,
			double tradingFeePercent, Set products) {
		this.account = account;
		this.created = created;
		this.fileName = fileName;
		this.total = total;
		this.taxPercent = taxPercent;
		this.tradingFeePercent = tradingFeePercent;
		this.products = products;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Timestamp getCreated() {
		return this.created;
	}

	public void setCreated(Timestamp created) {
		this.created = created;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

	public double getTaxPercent() {
		return this.taxPercent;
	}

	public void setTaxPercent(double taxPercent) {
		this.taxPercent = taxPercent;
	}

	public double getTradingFeePercent() {
		return this.tradingFeePercent;
	}

	public void setTradingFeePercent(double tradingFeePercent) {
		this.tradingFeePercent = tradingFeePercent;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
