package com.tuanc.auc.entities;
// Generated Feb 28, 2023, 1:38:45 AM by Hibernate Tools 6.1.5.Final

/**
 * ProductFile generated by hbm2java
 */
public class ProductFile implements java.io.Serializable {

	private Integer id;
	private Product product;
	private String name;
	private String type;
	private boolean isDefault;

	public ProductFile() {
	}

	public ProductFile(Product product, String name, String type, boolean isDefault) {
		this.product = product;
		this.name = name;
		this.type = type;
		this.isDefault = isDefault;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public boolean isIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(boolean isDefault) {
		this.isDefault = isDefault;
	}

}
