package com.tuanc.auc.entities;
// Generated Feb 28, 2023, 1:38:45 AM by Hibernate Tools 6.1.5.Final

/**
 * RecipientInformation generated by hbm2java
 */
public class RecipientInformation implements java.io.Serializable {

	private Integer id;
	private Account account;
	private String name;
	private String phoneNumber;
	private String address;
	private boolean isDefault;

	public RecipientInformation() {
	}

	public RecipientInformation(Account account, String name, String phoneNumber, String address, boolean isDefault) {
		this.account = account;
		this.name = name;
		this.phoneNumber = phoneNumber;
		this.address = address;
		this.isDefault = isDefault;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public boolean isIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(boolean isDefault) {
		this.isDefault = isDefault;
	}

}
