package com.tuanc.auc.entities;
// Generated Feb 28, 2023, 1:38:45 AM by Hibernate Tools 6.1.5.Final

import java.sql.Timestamp;

/**
 * TransactionHistory generated by hbm2java
 */
public class TransactionHistory implements java.io.Serializable {

	private int id;
	private Account account;
	private int amountOfMoney;
	private Timestamp time;
	private String paymentMethod;
	private double type;

	public TransactionHistory() {
	}

	public TransactionHistory(int id, Account account, int amountOfMoney, Timestamp time, String paymentMethod,
			double type) {
		this.id = id;
		this.account = account;
		this.amountOfMoney = amountOfMoney;
		this.time = time;
		this.paymentMethod = paymentMethod;
		this.type = type;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public int getAmountOfMoney() {
		return this.amountOfMoney;
	}

	public void setAmountOfMoney(int amountOfMoney) {
		this.amountOfMoney = amountOfMoney;
	}

	public Timestamp getTime() {
		return this.time;
	}

	public void setTime(Timestamp time) {
		this.time = time;
	}

	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	public double getType() {
		return this.type;
	}

	public void setType(double type) {
		this.type = type;
	}

}
