package com.tuanc.auc.entities;
// Generated Feb 28, 2023, 1:38:45 AM by Hibernate Tools 6.1.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer id;
	private String name;
	private String type;
	private Set auctions = new HashSet(0);
	private Set products = new HashSet(0);

	public Category() {
	}

	public Category(String name, String type) {
		this.name = name;
		this.type = type;
	}

	public Category(String name, String type, Set auctions, Set products) {
		this.name = name;
		this.type = type;
		this.auctions = auctions;
		this.products = products;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getAuctions() {
		return this.auctions;
	}

	public void setAuctions(Set auctions) {
		this.auctions = auctions;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
