package com.tuanc.auc.entities;
// Generated Feb 28, 2023, 1:38:45 AM by Hibernate Tools 6.1.5.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer id;
	private Invoice invoice;
	private Auction auction;
	private String name;
	private String description;
	private int quantity;
	private double startingPrice;
	private Double buyingPrice;
	private double stepIncrement;
	private Double estimatePrice;
	private double winnerPrice;
	private String certificateOfInspection;
	private boolean isValuation;
	private Timestamp endTime;
	private String status;
	private Set productFiles = new HashSet(0);
	private Set bidLogs = new HashSet(0);
	private Set categories = new HashSet(0);
	private Set accounts = new HashSet(0);

	public Product() {
	}

	public Product(Auction auction, String name, int quantity, double startingPrice, double stepIncrement,
			double winnerPrice, boolean isValuation, String status) {
		this.auction = auction;
		this.name = name;
		this.quantity = quantity;
		this.startingPrice = startingPrice;
		this.stepIncrement = stepIncrement;
		this.winnerPrice = winnerPrice;
		this.isValuation = isValuation;
		this.status = status;
	}

	public Product(Invoice invoice, Auction auction, String name, String description, int quantity,
			double startingPrice, Double buyingPrice, double stepIncrement, Double estimatePrice, double winnerPrice,
			String certificateOfInspection, boolean isValuation, Timestamp endTime, String status, Set productFiles,
			Set bidLogs, Set categories, Set accounts) {
		this.invoice = invoice;
		this.auction = auction;
		this.name = name;
		this.description = description;
		this.quantity = quantity;
		this.startingPrice = startingPrice;
		this.buyingPrice = buyingPrice;
		this.stepIncrement = stepIncrement;
		this.estimatePrice = estimatePrice;
		this.winnerPrice = winnerPrice;
		this.certificateOfInspection = certificateOfInspection;
		this.isValuation = isValuation;
		this.endTime = endTime;
		this.status = status;
		this.productFiles = productFiles;
		this.bidLogs = bidLogs;
		this.categories = categories;
		this.accounts = accounts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Invoice getInvoice() {
		return this.invoice;
	}

	public void setInvoice(Invoice invoice) {
		this.invoice = invoice;
	}

	public Auction getAuction() {
		return this.auction;
	}

	public void setAuction(Auction auction) {
		this.auction = auction;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public double getStartingPrice() {
		return this.startingPrice;
	}

	public void setStartingPrice(double startingPrice) {
		this.startingPrice = startingPrice;
	}

	public Double getBuyingPrice() {
		return this.buyingPrice;
	}

	public void setBuyingPrice(Double buyingPrice) {
		this.buyingPrice = buyingPrice;
	}

	public double getStepIncrement() {
		return this.stepIncrement;
	}

	public void setStepIncrement(double stepIncrement) {
		this.stepIncrement = stepIncrement;
	}

	public Double getEstimatePrice() {
		return this.estimatePrice;
	}

	public void setEstimatePrice(Double estimatePrice) {
		this.estimatePrice = estimatePrice;
	}

	public double getWinnerPrice() {
		return this.winnerPrice;
	}

	public void setWinnerPrice(double winnerPrice) {
		this.winnerPrice = winnerPrice;
	}

	public String getCertificateOfInspection() {
		return this.certificateOfInspection;
	}

	public void setCertificateOfInspection(String certificateOfInspection) {
		this.certificateOfInspection = certificateOfInspection;
	}

	public boolean isIsValuation() {
		return this.isValuation;
	}

	public void setIsValuation(boolean isValuation) {
		this.isValuation = isValuation;
	}

	public Timestamp getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Timestamp endTime) {
		this.endTime = endTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getProductFiles() {
		return this.productFiles;
	}

	public void setProductFiles(Set productFiles) {
		this.productFiles = productFiles;
	}

	public Set getBidLogs() {
		return this.bidLogs;
	}

	public void setBidLogs(Set bidLogs) {
		this.bidLogs = bidLogs;
	}

	public Set getCategories() {
		return this.categories;
	}

	public void setCategories(Set categories) {
		this.categories = categories;
	}

	public Set getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set accounts) {
		this.accounts = accounts;
	}

}
