package com.tuanc.auc.entities;
// Generated Feb 28, 2023, 1:38:45 AM by Hibernate Tools 6.1.5.Final

/**
 * SellerUpgrade generated by hbm2java
 */
public class SellerUpgrade implements java.io.Serializable {

	private Integer id;
	private String name;
	private double price;
	private String description;
	private int auctionQuantity;
	private int auctionSQuantity;
	private int auctionInMonth;
	private int auctionSInMonth;
	private int vipPostQuantity;
	private boolean status;

	public SellerUpgrade() {
	}

	public SellerUpgrade(String name, double price, String description, int auctionQuantity, int auctionSQuantity,
			int auctionInMonth, int auctionSInMonth, int vipPostQuantity, boolean status) {
		this.name = name;
		this.price = price;
		this.description = description;
		this.auctionQuantity = auctionQuantity;
		this.auctionSQuantity = auctionSQuantity;
		this.auctionInMonth = auctionInMonth;
		this.auctionSInMonth = auctionSInMonth;
		this.vipPostQuantity = vipPostQuantity;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getAuctionQuantity() {
		return this.auctionQuantity;
	}

	public void setAuctionQuantity(int auctionQuantity) {
		this.auctionQuantity = auctionQuantity;
	}

	public int getAuctionSQuantity() {
		return this.auctionSQuantity;
	}

	public void setAuctionSQuantity(int auctionSQuantity) {
		this.auctionSQuantity = auctionSQuantity;
	}

	public int getAuctionInMonth() {
		return this.auctionInMonth;
	}

	public void setAuctionInMonth(int auctionInMonth) {
		this.auctionInMonth = auctionInMonth;
	}

	public int getAuctionSInMonth() {
		return this.auctionSInMonth;
	}

	public void setAuctionSInMonth(int auctionSInMonth) {
		this.auctionSInMonth = auctionSInMonth;
	}

	public int getVipPostQuantity() {
		return this.vipPostQuantity;
	}

	public void setVipPostQuantity(int vipPostQuantity) {
		this.vipPostQuantity = vipPostQuantity;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

}
