package com.tuanc.auc.entities;
// Generated Feb 28, 2023, 1:38:45 AM by Hibernate Tools 6.1.5.Final

/**
 * SellerDetail generated by hbm2java
 */
public class SellerDetail implements java.io.Serializable {

	private Integer id;
	private Account account;
	private int auctionQuantity;
	private int auctionSQuantity;
	private int auctionInMonth;
	private int auctionSInMonth;
	private String rank;
	private int vipPostQuantity;
	private String type;

	public SellerDetail() {
	}

	public SellerDetail(Account account, int auctionQuantity, int auctionSQuantity, int auctionInMonth,
			int auctionSInMonth, String rank, int vipPostQuantity, String type) {
		this.account = account;
		this.auctionQuantity = auctionQuantity;
		this.auctionSQuantity = auctionSQuantity;
		this.auctionInMonth = auctionInMonth;
		this.auctionSInMonth = auctionSInMonth;
		this.rank = rank;
		this.vipPostQuantity = vipPostQuantity;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public int getAuctionQuantity() {
		return this.auctionQuantity;
	}

	public void setAuctionQuantity(int auctionQuantity) {
		this.auctionQuantity = auctionQuantity;
	}

	public int getAuctionSQuantity() {
		return this.auctionSQuantity;
	}

	public void setAuctionSQuantity(int auctionSQuantity) {
		this.auctionSQuantity = auctionSQuantity;
	}

	public int getAuctionInMonth() {
		return this.auctionInMonth;
	}

	public void setAuctionInMonth(int auctionInMonth) {
		this.auctionInMonth = auctionInMonth;
	}

	public int getAuctionSInMonth() {
		return this.auctionSInMonth;
	}

	public void setAuctionSInMonth(int auctionSInMonth) {
		this.auctionSInMonth = auctionSInMonth;
	}

	public String getRank() {
		return this.rank;
	}

	public void setRank(String rank) {
		this.rank = rank;
	}

	public int getVipPostQuantity() {
		return this.vipPostQuantity;
	}

	public void setVipPostQuantity(int vipPostQuantity) {
		this.vipPostQuantity = vipPostQuantity;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
