package com.tuanc.auc.entities;
// Generated Feb 28, 2023, 1:38:45 AM by Hibernate Tools 6.1.5.Final

/**
 * Ticket generated by hbm2java
 */
public class Ticket implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Auction auction;
	private boolean isActived;

	public Ticket() {
	}

	public Ticket(Auction auction, boolean isActived) {
		this.auction = auction;
		this.isActived = isActived;
	}

	public Ticket(Account account, Auction auction, boolean isActived) {
		this.account = account;
		this.auction = auction;
		this.isActived = isActived;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Auction getAuction() {
		return this.auction;
	}

	public void setAuction(Auction auction) {
		this.auction = auction;
	}

	public boolean isIsActived() {
		return this.isActived;
	}

	public void setIsActived(boolean isActived) {
		this.isActived = isActived;
	}

}
